-- AlterTable
ALTER TABLE "PaymentConfig" ADD COLUMN     "mpEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "mpAccessToken" TEXT,
ADD COLUMN     "mpFeeMode" TEXT NOT NULL DEFAULT 'TENANT',
ADD COLUMN     "mpFeePercent" DECIMAL(5,2) NOT NULL DEFAULT 3.99,
ADD COLUMN     "mpFeeFixed" DECIMAL(8,2) NOT NULL DEFAULT 1.00,
ADD COLUMN     "mpFeeIgv" BOOLEAN NOT NULL DEFAULT true;
